### ISSUE TITLE
ASMARA  Wont do more the 299 Monitors

### ISSUE THREAD

**Issue by WhoIsAsking1996** [A-c0rN/ASMARA#48]
Hello i am trying to run more then 299 monitors on my server with Dual AMD 7551 CPUs

**Comment by secludedhusky** [comment]
ASMARA is entirely dependent on RAM/Memory. It has nothing to do with CPU power. Since ASMARA uses FFMPEG and FFMPEG eats through a lot of ram, most likely you're RAM limited and not CPU limited.

And there's nothing that the developers of this project can help you with as its an ffmpeg issue and not an ASMARA issue.
